name: PyInstaller Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip
        pip install -r requirements.txt
    - name: build with pyinstaller
      run: |
        pyinstaller px100.spec
    - name: Build NSIS installer package
      run: |
        makensis -VERSION
        makensis px100.nsi
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: px100
        path: dist/*
    - name: Upload installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: installer
        path: Install*
